"""Generate research figures, an eight-page memo, and an offline results explorer."""
from pathlib import Path
import base64,hashlib,html,json,struct,zipfile
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.collections import PolyCollection
from reportlab.platypus import SimpleDocTemplate,Paragraph,Spacer,Table,TableStyle,Image,PageBreak
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet,ParagraphStyle
from reportlab.lib.enums import TA_LEFT
from reportlab.lib.units import inch
ROOT=Path(__file__).resolve().parent; O=ROOT/'output'; R=ROOT/'reports'; D=ROOT/'docs'
R.mkdir(exist_ok=True);D.mkdir(exist_ok=True);(D/'assets').mkdir(exist_ok=True)
audit=json.loads((O/'data_audit.json').read_text())
rep=pd.read_csv(O/'s16_reconciliation.csv'); ext=pd.read_csv(O/'baseline_access_extension.csv'); con=pd.read_csv(O/'post2011_contrasts.csv'); sens=pd.read_csv(O/'radius_sensitivity.csv'); rawext=pd.read_csv(O/'raw_unit_extension.csv')
plt.rcParams.update({'font.family':'DejaVu Sans','font.size':10,'axes.spines.top':False,'axes.spines.right':False,'axes.spines.left':False,'axes.edgecolor':'#bbc8ce','axes.titleweight':'bold','axes.labelcolor':'#243b45','text.color':'#243b45','xtick.color':'#49616d','ytick.color':'#49616d','figure.facecolor':'white','axes.facecolor':'white','savefig.facecolor':'white'})
TEAL='#007f80';BLUE='#2f5d91';ORANGE='#ba7236'

def finish(fig,name):
 fig.savefig(D/'assets'/f'{name}.png',dpi=190,bbox_inches='tight');plt.close(fig)

fig,ax=plt.subplots(figsize=(8.5,4.1)); pos=np.arange(len(rep));
ax.errorbar(rep.estimate,pos,xerr=[rep.estimate-rep.ci_low,rep.ci_high-rep.estimate],fmt='o',color=TEAL,capsize=3,label='Python estimate and 95% CI')
ax.scatter(rep.published_estimate,pos,marker='x',s=48,color=ORANGE,label='Published rounded coefficient',zorder=4)
ax.set_yticks(pos,rep.outcome);ax.invert_yaxis();ax.axvline(0,color='#adb8bd',linewidth=1);ax.set_xlabel('Binary post-period exposure coefficient, archive outcome units');ax.legend(loc='lower right',frameon=False,fontsize=8);ax.set_title('Eight appendix estimates reproduced');fig.tight_layout();finish(fig,'replication')
fig,ax=plt.subplots(figsize=(8.5,3.8));show=con[con.outcome.isin(['Public primary schools','Public secondary schools'])]
for i,label in enumerate(show.outcome.unique()):
 a=show[show.outcome==label];xp=np.arange(len(a))+(i-.5)*.10
 ax.errorbar(xp,a.estimate,yerr=[a.estimate-a.ci_low,a.ci_high-a.estimate],fmt='o',capsize=4,color=[TEAL,BLUE][i],label=label)
ax.axhline(0,color='#adb8bd',linewidth=1);ax.set_xticks([0,1],['2016 vs 2011','2020 vs 2011']);ax.set_ylabel('Change in exposure slope, archive units');ax.set_title('School-access relationships strengthen by 2020');ax.legend(frameon=False,fontsize=9);fig.tight_layout();finish(fig,'school_contrasts')
fig,ax=plt.subplots(figsize=(8.5,3.8));a=ext[(ext.outcome=='Public primary schools')&(ext.group!='Difference between groups')]
for i,g in enumerate(a.group.unique()):
 b=a[a.group==g];xp=np.arange(len(b))+(i-.5)*.12
 ax.errorbar(xp,b.estimate,yerr=[b.estimate-b.ci_low,b.ci_high-b.estimate],fmt='o',capsize=4,color=[BLUE,TEAL][i],label=g)
ax.axhline(0,color='#adb8bd',linewidth=1);ax.set_xticks([0,1],['2016 vs 2011','2020 vs 2011']);ax.set_ylabel('Change in primary-school exposure slope');ax.set_title('Baseline access: positive 2020 contrasts in both groups');ax.legend(frameon=False,fontsize=8);fig.tight_layout();finish(fig,'extension')
fig,ax=plt.subplots(figsize=(8.5,3.5));
for i,label in enumerate(sens.outcome.unique()):
 b=sens[(sens.outcome==label)&(sens.post_year==2020)];xp=b.radius_km+(i-.5)*4
 ax.errorbar(xp,b.estimate,yerr=[b.estimate-b.ci_low,b.ci_high-b.estimate],fmt='o',capsize=4,color=[TEAL,BLUE][i],label=label)
ax.axhline(0,color='#adb8bd',linewidth=1);ax.set_xticks([100,150,200]);ax.set_xlabel('Distance cutoff to settlements active in 2001 (km)');ax.set_ylabel('2020 minus 2011 exposure slope');ax.set_title('Primary-school contrasts persist across radius choices');ax.legend(frameon=False,fontsize=8);fig.tight_layout();finish(fig,'radius')

# Minimal, documented DBF/SHP reader for the single verified Polygon archive.
# No geography reconstruction from names: align records using the original P_02_ID key.
def read_polygons():
 z=zipfile.ZipFile(ROOT/'data/raw/uganda_2002_dissolve4.zip'); dbf=z.read(next(n for n in z.namelist() if n.endswith('.dbf'))); shp=z.read(next(n for n in z.namelist() if n.endswith('.shp')))
 count=struct.unpack('<I',dbf[4:8])[0];hlen,rlen=struct.unpack('<HH',dbf[8:12]);ids=[int(dbf[hlen+i*rlen+1:hlen+(i+1)*rlen].decode().strip()) for i in range(count)]
 pos=100;records=[]
 while pos<len(shp):
  size=struct.unpack('>i',shp[pos+4:pos+8])[0]*2;record=shp[pos+8:pos+8+size];pos+=8+size
  typ=struct.unpack('<i',record[:4])[0]
  if typ!=5: raise ValueError(f'Expected polygon type 5, found {typ}')
  nparts,npoints=struct.unpack('<ii',record[36:44]);starts=struct.unpack('<'+'i'*nparts,record[44:44+4*nparts]);points=np.frombuffer(record[44+4*nparts:],dtype='<f8',count=npoints*2).reshape(-1,2)
  records.append([points[a:b].copy() for a,b in zip(starts,list(starts[1:])+[npoints])])
 if len(ids)!=len(records) or len(set(ids))!=5378: raise ValueError('Geographic key mismatch')
 return dict(zip(ids,records))
polys=read_polygons();panel=pd.read_csv(O/'analysis_panel.csv.gz'); latest=panel[panel.year==2020].set_index('parish_id');paths=[];values=[]
for pid,parts in polys.items():
 value=latest.loc[pid,'presence'] if pid in latest.index and latest.loc[pid,'min_distance_01']<150 else np.nan
 for part in parts: paths.append(part);values.append(value)
fig,ax=plt.subplots(figsize=(7.2,5.0));coll=PolyCollection(paths,array=np.array(values),cmap='viridis',edgecolors='none');coll.cmap.set_bad('#e2e7e9');ax.add_collection(coll);ax.autoscale();ax.set_aspect('equal');ax.set_xlabel('Longitude');ax.set_ylabel('Latitude');ax.set_title('2020 refugee presence across study parishes');fig.colorbar(coll,ax=ax,label='Transformed presence, standardized over full panel',shrink=.76);fig.tight_layout();finish(fig,'presence_map')
(O/'geographic_join_audit.json').write_text(json.dumps({'boundary_records':len(polys),'unique_geographic_ids':len(polys),'panel_parishes':int(panel.parish_id.nunique()),'all_panel_ids_found':bool(set(panel.parish_id).issubset(polys)),'crs':'WGS84 geographic coordinates','map_gray':'Outside 150km study sample or missing controls'},indent=2))

styles=getSampleStyleSheet();styles.add(ParagraphStyle(name='BodyMemo',fontName='Helvetica',fontSize=10.2,leading=14.7,spaceAfter=10,textColor=colors.HexColor('#243b45')));styles.add(ParagraphStyle(name='Kicker',fontName='Helvetica-Bold',fontSize=9,leading=12,textColor=colors.HexColor(TEAL),spaceAfter=14));styles.add(ParagraphStyle(name='MemoTitle',fontName='Helvetica-Bold',fontSize=25,leading=29,textColor=colors.HexColor('#163a48'),spaceAfter=18));styles['Heading1'].fontSize=17;styles['Heading1'].leading=21;styles['Heading1'].textColor=colors.HexColor('#163a48');styles['Heading1'].spaceAfter=15;styles['Heading2'].fontSize=12;styles['Heading2'].leading=16
story=[];md=[]
def p(text): story.append(Paragraph(text,styles['BodyMemo']));md.append(text.replace('<b>','').replace('</b>',''))
def h(title):story.append(Paragraph(title,styles['Heading1']));md.append('\n## '+title)
def page():story.append(PageBreak())
def chart(name,width=6.7):
 from PIL import Image as PILImage
 f=D/'assets'/f'{name}.png'; w,h0=PILImage.open(f).size;story.append(Image(str(f),width=width*inch,height=width*inch*h0/w));story.append(Spacer(1,9));md.append(f'\n![{name}](../docs/assets/{name}.png)')
def table(rows,widths):
 data=[[Paragraph(str(c),styles['BodyMemo']) for c in row] for row in rows]
 t=Table(data,colWidths=[x*inch for x in widths],repeatRows=1,hAlign='LEFT');t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),colors.HexColor('#e5eeee')),('VALIGN',(0,0),(-1,-1),'TOP'),('LINEBELOW',(0,0),(-1,0),.5,colors.HexColor(TEAL)),('BOTTOMPADDING',(0,0),(-1,-1),5),('TOPPADDING',(0,0),(-1,-1),5)]));story.append(t);story.append(Spacer(1,12));md.append('\n'+'\n'.join(' | '.join(map(str,row)) for row in rows))
def fmt(x):return f'{x:.3f}'

story.append(Paragraph('INDEPENDENT REPLICATION AND EXPLORATORY EXTENSION',styles['Kicker']))
story.append(Paragraph('Refugee Hosting and<br/>Local Development<br/>in Uganda',styles['MemoTitle']))
p('<b>Research portfolio memorandum</b><br/>Prepared for Nicholas Reign Lugu<br/>8 October 2026')
p('This project reproduces selected public-service estimates from Zhou, Grossman, and Ge (2023) and examines whether changes in the relationship between refugee presence and school access differ with initial primary-school access. The evidence comes from the authors\' public replication archive, rather than newly collected administrative records.')
h('Principal findings')
p('The Python implementation reproduces all eight coefficients, clustered standard errors, and sample sizes in supplementary Table S16 at its published three-decimal precision. This is a selected-table replication, not a reproduction of the entire paper or of its public-opinion and health-utilization analyses.')
p('In the continuous-presence specification, the 2020-versus-2011 primary-school slope contrast is 0.048 archive-standardized units (95% CI 0.022 to 0.073). Both baseline-access groups have positive estimated contrasts. Their difference is -0.027 (95% CI -0.058 to 0.003), so this standardized specification does not establish a difference at the 5% level.')
p('A raw-unit sensitivity analysis gives a different inference for the group difference. The project therefore treats heterogeneity as specification-sensitive. Findings describe an exposure relationship in a refugee-hosting and aid context, with causal interpretation dependent on demanding observational assumptions.')
p('<b>Contribution:</b> transparent econometric translation, quantitative reconciliation, geographic linkage, an exploratory heterogeneity analysis, and a documented reproduction workflow. This independent portfolio project has no institutional affiliation or endorsement from the original authors or Dartmouth.')
page();h('1. Research question and study design')
p('The substantive question is how host communities\' public services change as refugee presence increases. A useful extension asks whether communities starting with lower service access experience a different change in this relationship. Such a distinction could inform further research on the distribution of development benefits, but this dataset cannot identify an optimal aid allocation rule.')
p('The source study combines settlement population and distance measures with parish-level service indicators and baseline covariates. The released panel has 5,378 parishes observed in 2001, 2006, 2011, 2016, and 2020. The five waves are not annual observations, and 2014 is not an observed wave. The authors motivate pre/post comparisons around the large inflow and policy context of the mid-2010s [1].')
p('This project has two distinct tasks. The confirmatory reproduction task follows the archived S16 code, including its treatment classification and exclusions. The exploratory task adds heterogeneity by baseline school access to the continuous-presence model. Its primary outcome is the archive-standardized public primary-school measure, with secondary schools as a comparator. The extension was selected after reviewing the source data and code, before fitting its models. It was not externally preregistered.')
chart('presence_map',5.5)
p('<b>Figure 1.</b> Original parish boundaries joined by P_02_ID to parish_id. Color represents 2020 presence, not a causal effect. Gray denotes locations outside the study radius or excluded for missing baseline controls. Geographic data use WGS84 coordinates.')
page();h('2. Data management and measurement')
p('The immutable source CSV has 26,890 records and 248 variables. The pipeline checks the parish-year key and expected waves, records source checksums, and retains the original raw file. There are no duplicate keys. Excluding records with missing baseline controls or contemporaneous settlement distance removes 1,055 rows, leaving 25,835. The 150km study restriction retains 18,185 rows from 3,637 parishes.')
table([['Check','Observed result'],['Panel structure','5,378 parishes x 5 waves'],['Duplicate parish-year keys','0'],['Incomplete baseline controls/distance','1,055 rows excluded'],['Complete records within study radius','18,185 rows / 3,637 parishes'],['S16 extra treatment exclusions','7 rows outside archived bin boundaries'],['Geographic linkage','5,378 boundary keys; all retained panel keys found']],[3.7,2.7])
p('The pipeline constructs Nearest + 20 presence exactly as the archived model code specifies: use the inverse-hyperbolic-sine transform of the aggregate exposure measure within 20km when the closest settlement is within 20km, otherwise transform nearest-settlement exposure. It standardizes this variable over the full released panel before control and radius exclusions. The analysis sample uses min_distance_01, distance to settlements active in 2001. Those two distances serve different purposes.')
p('S16 bins Nearest + 20 using quantiles of standardized Nearest, rather than quantiles of Nearest + 20 itself. Seven records fall outside these bin bounds. This implementation preserves that behavior to reproduce S16 and documents it explicitly. The binary classification is time-varying across post-period waves. It should not be interpreted as a fixed, randomly assigned treatment group.')
p('Primary-school standardized outcomes have mean approximately zero and standard deviation one within each wave. They express relative positions within a year. Secondary-school units follow the supplied archive variable. Raw school measures are schools per thousand school-age children. Denominator changes can lower these ratios even if school counts rise. Health-tier standardized variables are missing in 2020, while roads are missing before 2011. No imputation fills these structural gaps.')
page();h('3. Econometric implementation and identification')
p('The continuous specification fits OLS with parish fixed effects and region-by-wave fixed effects. Refugee presence enters as a baseline term plus interactions with the 2006, 2011, 2016, and 2020 wave indicators. Thirteen baseline controls interact with available wave indicators. The controls cover census demographics and economic conditions, prior violence, and distances to oil, borders, roads, and the capital. Health and road models use the corresponding available waves.')
p('<b>Model:</b> y_it = parish_i + region_wave_rt + b0 presence_it + sum_t b_t presence_it x wave_t + sum_t c_t controls_i x wave_t + error_it.')
p('A post-2011 contrast is the difference between the 2020 or 2016 presence interaction coefficient and its 2011 counterpart. It measures a change in the conditional exposure slope. Because presence is continuous and time-varying, this is not a conventional event-study average treatment effect on a fixed treated population. Changing exposure distributions or heterogeneous responses may also change the interpretation of the slope.')
p('Alternating projections remove fixed effects without constructing thousands of dummy variables. Column scaling and pivoted QR identify estimable regressors. The covariance estimator clusters by parish and applies a reghdfe-style small-sample correction that avoids counting parish effects nested inside the same clustering unit twice. Confidence intervals use a t distribution with G-1 degrees of freedom. Linear contrasts use the full covariance matrix, including covariance between coefficient estimates.')
p('The supplemental binary model uses parish and pre/post-period effects, wave-interacted controls, and the archived post-period exposure indicator. Region effects are redundant with parish effects. All eight published S16 results provide an external numerical benchmark. A separate unit test compares absorbed OLS coefficients against explicit dummy-variable OLS on an unbalanced artificial panel.')
p('Causal interpretation requires an appropriate conditional parallel-trends restriction, limited anticipation and spillovers, no unmeasured time-varying confounding linked to exposure, and comparable outcome measurement. Settlement placement is not random. Refugee hosting, humanitarian funding, and government responses occur together, so these estimates do not isolate the effect of refugees alone. Parish clustering also does not resolve possible dependence across nearby parishes. Additional spatial inference and design diagnostics would strengthen the analysis.')
page();h('4. Published-table reconciliation')
chart('replication',6.7)
p('<b>Figure 2.</b> Supplementary Table S16 reproduction. The displayed units differ across outcomes. A common horizontal axis helps compare signs but does not imply that the measures share a substantive scale. The public-goods index remains in archive index units.')
rows=[['Outcome','Published','Python','N']]
for _,a in rep.iterrows():rows.append([a.outcome,fmt(a.published_estimate)+' ('+fmt(a.published_se)+')',fmt(a.estimate)+' ('+fmt(a.se)+')',f'{int(a.n):,}'])
table(rows,[2.4,1.4,1.4,1.2])
p('Parentheses show parish-cluster standard errors. All eight estimates and standard errors round to the published values, and all eight sample sizes agree. Matching a rounded table establishes reproducibility at that precision. It does not establish exact machine-level agreement with the original R run, verify every upstream transformation, or independently validate the source records.')
p('Results vary across service tiers. The reproduced binary coefficient is positive for primary schools, roads, HC3, HC5, and the index. HC2 and HC4 are negative. The secondary-school coefficient is small and uncertain. A single claim that all services improved would obscure this variation.')
page();h('5. Continuous exposure and baseline-access extension')
chart('extension',6.6)
p('<b>Figure 3.</b> Differences in the continuous exposure slope relative to 2011, by baseline primary-school access. Intervals are pointwise parish-cluster 95% intervals. They are not adjusted for multiple comparisons.')
p('The baseline moderator is a parish\'s raw public-primary-school access in 2001. The threshold is the median across all parishes with complete baseline controls: 2.174 schools per thousand primary-age children. At/below-median and above-median status remain fixed over time. This threshold is determined before applying the 150km radius, and the release includes the value needed to reproduce it.')
p('The extension adds presence-by-baseline-group terms, their wave interactions, and baseline-group-by-wave terms. The latter allow group-specific common trends. The model retains all original baseline-control interactions and fixed effects. A raw-unit robustness check changes the outcome scale while retaining the same moderator and specification.')
table([['Primary schools, 2020 vs 2011','Estimate','95% CI'],['Above-median baseline access','0.055','0.019 to 0.090'],['At/below-median baseline access','0.027','0.009 to 0.046'],['Difference: lower minus higher access','-0.027','-0.058 to 0.003']],[3.8,1.1,1.5])
p('Both group estimates are positive, but comparing their separate significance levels is not a test of heterogeneity. The direct interaction contrast has p = 0.077, and its interval crosses zero. The standardized specification therefore supplies suggestive, imprecise evidence rather than a firm conclusion that one group benefits more.')
p('In raw primary-school units, the 2020 group-difference contrast is -0.120 schools per thousand children per one-SD increase in transformed presence (95% CI -0.217 to -0.024; p = 0.014). Different wave standardizations change the estimand, so this result is not interchangeable with the standardized contrast. The secondary-school group difference remains uncertain on both scales. These exploratory p-values require caution given the set of comparisons and specification sensitivity.')
page();h('6. Robustness, competing interpretations, and limits')
chart('radius',6.6)
p('<b>Figure 4.</b> Continuous-model 2020-versus-2011 exposure-slope contrasts using 100km, 150km, and 200km radius samples. Presence remains standardized over the original full panel across specifications.')
p('The primary-school contrast is positive under all three radius choices, approximately 0.054, 0.048, and 0.046, respectively. The secondary-school interval crosses zero at 200km, illustrating greater sensitivity. Radius changes alter the sampled population as well as geographic reach. Stability across these cutoffs is useful, but it does not validate the identifying assumptions.')
p('Raw nationwide average primary-school access falls from 2.706 schools per thousand children in 2001 to 1.630 in 2020. Positive relative exposure relationships can coexist with such an aggregate decline. This descriptive series is unweighted across parishes, not a national child-weighted access estimate, and cannot establish whether refugee hosting caused the decline.')
p('The binary S16 coefficient and the continuous post-2011 contrasts answer different questions. For example, the index\'s reproduced binary coefficient is positive, whereas the continuous 2020-versus-2011 slope contrast is negative. This difference should trigger attention to exposure classification, timing, outcome composition, and functional form. It is not evidence that one implementation failed, and it prevents a blanket summary of uniform improvement.')
p('This release does not estimate public attitudes, humanitarian-aid mechanisms, individual health utilization, or employment effects. It also does not rebuild school and settlement geocoding from the original primary records. Any explanation involving those outcomes or mechanisms requires additional data and separate validation. Exclusions depend on baseline-control completeness, which may limit generalizability.')
p('Further priorities include reconstructing raw outcome definitions, testing pre-period implications appropriate to continuous exposure, examining overlap and influential locations, adding spatially robust inference, and evaluating common-scale outcomes. These steps are listed as unfinished research work rather than presented as checks already completed.')
page();h('7. Reproducibility, research practice, and references')
p('The repository separates raw inputs, archived author code, original Python code, machine-readable results, and presentation outputs. run_analysis.py creates the analysis tables and provenance record; build_outputs.py creates figures and the memo. Source hashes identify the exact release. Five automated tests cover fixed-effect absorption, agreement with dummy OLS, covariance-aware contrasts, panel integrity, and published-table reconciliation.')
p('The downloadable package includes the real public-data inputs required for offline execution. A minimal teaching notebook introduces absorption and contrast construction. The results explorer exposes the numerical evidence, measurement caveats, and scope, rather than presenting uncertain observational estimates as policy targets. The seminar presentation summarizes the question and opens discussion of identification and outcome scales.')
p('<b>AI disclosure.</b> OpenAI Codex assisted with source inspection, code development, drafting, and verification. Numerical estimates come from executing the supplied Python code against the archived CSV. The package does not claim Claude Code use, original fieldwork, independent human peer review, or endorsement by the study authors. The applicant should review the code and interpretation before using this work in an application or describing personal contributions.')
p('<b>Research coordination.</b> Completed work comprises source acquisition, selected-model translation, S16 reconciliation, exploratory estimation, and output generation. Open tasks include a full original-R execution, original-record data audit, broader identification diagnostics, spatial inference, and public-opinion replication. A workplan and decision log record these boundaries for future collaborators.')
p('<b>[1]</b> Zhou, Yang-Yang, Guy Grossman, and Shuning Ge. 2023. Inclusive refugee-hosting can improve local development and prevent public backlash. <i>World Development</i> 166: 106203. https://doi.org/10.1016/j.worlddev.2023.106203.')
p('<b>[2]</b> Zhou, Yang-Yang, Guy Grossman, and Shuning Ge. 2023. Replication Data for the above article. Harvard Dataverse, version 1.0. https://doi.org/10.7910/DVN/TXSZDC. Sources used: political_data_merged_Dev_Econ_Paper, Refugee_dev_Paper.Rnw, Refugee_dev_SI.Rnw, README.rtf, clean_parish_data_development_v4.R, and uganda_2002_dissolve4.zip. Accessed 8 October 2026. The archive displays CC0 1.0 terms. Original authors receive full attribution.')
p('<b>Benchmark location.</b> Supplementary appendix, Table S16 and section S2.4. The supplementary Rnw code supplies the exact binning, controls, sample selection, and regression specification. The public author-hosted appendix is linked in the project source register.')
p('<b>Reproduction commands:</b> python -m pip install -r requirements.txt; python run_analysis.py; python -m unittest discover -s tests -v; python build_outputs.py. The checked environment uses Python 3.12 and the versions recorded in output/run_manifest.json.')

def footer(canvas,doc):
 canvas.saveState();canvas.setStrokeColor(colors.HexColor('#cad5d8'));canvas.line(43,40,569,40);canvas.setFont('Helvetica',8);canvas.setFillColor(colors.HexColor('#49616d'));canvas.drawString(43,27,'UGANDA REFUGEE HOSTING  /  INDEPENDENT RESEARCH PORTFOLIO');canvas.drawRightString(569,27,str(doc.page));canvas.restoreState()
SimpleDocTemplate(str(R/'Uganda_Refugee_Hosting_Research_Memo.pdf'),pagesize=(612,792),rightMargin=43,leftMargin=43,topMargin=42,bottomMargin=52,title='Refugee Hosting and Local Development in Uganda',author='Prepared for Nicholas Reign Lugu').build(story,onFirstPage=footer,onLaterPages=footer)
(R/'research_memo.md').write_text('\n\n'.join(md))

# Self-contained explorer can be opened directly without a server or CDN.
def embedded(name):return 'data:image/png;base64,'+base64.b64encode((D/'assets'/f'{name}.png').read_bytes()).decode()
records=rep.to_dict('records');extrecords=ext.to_dict('records')
pagehtml='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Uganda Refugee Hosting Research</title><style>
:root{--ink:#173a49;--teal:#087b7e;--muted:#536873}*{box-sizing:border-box}body{margin:0;background:#f5f7f7;color:var(--ink);font:16px/1.6 system-ui,sans-serif}header{background:#143a48;color:white;padding:64px max(6vw,24px) 48px}header small{letter-spacing:.16em;color:#9dd8d0}h1{font-size:clamp(32px,5vw,58px);line-height:1.12;max-width:850px;margin:20px 0}header p{max-width:750px;color:#d6e6e9}main{max-width:1120px;margin:auto;padding:32px 24px 65px}section{margin:24px 0 48px}h2{font-size:28px;line-height:1.25}h3{font-size:19px}figure{margin:20px 0;background:white;padding:20px;border:1px solid #d8e2e4}img{max-width:100%;height:auto}figcaption{font-size:13px;color:var(--muted)}.metrics{display:flex;gap:38px;flex-wrap:wrap;padding:22px 0;border-bottom:1px solid #c8d7db}.metric strong{font-size:32px;display:block}.metric span{font-size:14px}.note{border-left:4px solid var(--teal);padding:14px 20px;background:#e8f1ef}.tablewrap{overflow:auto}table{border-collapse:collapse;width:100%;background:white;font-size:14px}th,td{text-align:left;padding:12px;border-bottom:1px solid #dbe4e7}th{background:#e7eeee}label{font-weight:600}select{font:inherit;padding:8px;margin:8px 12px;background:white;border:1px solid #a5b8bf}a{color:#087b7e}header a{color:#c0efe6}.grid{display:grid;grid-template-columns:1fr 1fr;gap:28px}.grid figure{align-self:start}footer{font-size:13px;color:var(--muted);margin-top:40px}@media(max-width:760px){.grid{display:block}header{padding-top:38px}.metrics{gap:24px}th,td{padding:8px}}
</style><header><small>INDEPENDENT REPLICATION + EXPLORATORY EXTENSION</small><h1>Refugee hosting and local development in Uganda</h1><p>A reproducible econometric portfolio using the public archive of Zhou, Grossman, and Ge (2023). Prepared for Nicholas Reign Lugu.</p><p>Selected-table replication. Observational evidence. No institutional affiliation or endorsement.</p></header><main>
<div class="metrics"><div class="metric"><strong>26,890</strong><span>Real parish-wave records</span></div><div class="metric"><strong>5,378</strong><span>Parishes in the source panel</span></div><div class="metric"><strong>8 / 8</strong><span>Published table estimates reconciled</span></div><div class="metric"><strong>5</strong><span>Automated tests passed</span></div></div>
<section><h2>The research question</h2><p>How does the relationship between refugee presence and school access change over time, and does that change differ with initial primary-school access?</p><div class="note"><b>Main interpretation:</b> the primary-school exposure relationship strengthens by 2020. The standardized extension does not establish a difference between baseline-access groups at the 5% level. A raw-unit check changes that inference, so heterogeneity remains specification-sensitive.</div></section>
<section><h2>Geography and reproducible evidence</h2><div class="grid"><figure><img src="MAP" alt="Map of 2020 standardized refugee presence across original Uganda parish boundaries"><figcaption>Original parish keys join the data to WGS84 boundaries. Gray indicates exclusion from the 150km sample or missing baseline controls. Colors show exposure, not effects.</figcaption></figure><div><h3>What was reproduced</h3><p>All eight coefficients, parish-cluster standard errors, and sample sizes in supplementary Table S16 agree at published precision.</p><p>The model reproduces the archived time-varying binary classification. It uses pre/post and parish effects plus baseline controls interacted with wave.</p><h3>Scope</h3><p>This release covers public-service outcomes. Public opinion, health utilization, aid mechanisms, and a full original-R execution remain outside the completed scope.</p></div></div></section>
<section><h2>Published-table reconciliation</h2><figure><img src="REP" alt="Eight replicated appendix coefficients and confidence intervals"><figcaption>Outcome scales differ. Positive values cannot be compared as a common magnitude of service improvement.</figcaption></figure><div class="tablewrap"><table><thead><tr><th>Outcome</th><th>Published</th><th>Python</th><th>SE</th><th>Records</th><th>Match</th></tr></thead><tbody id="repbody"></tbody></table></div></section>
<section><h2>Baseline-access extension</h2><p>The baseline moderator is primary-school access in 2001, split at 2.174 schools per thousand children. The model adds group-specific wave and exposure terms.</p><label for="outcome">Outcome</label><select id="outcome"><option>Public primary schools</option><option>Public secondary schools</option></select><label for="year">Contrast</label><select id="year"><option value="2020">2020 vs 2011</option><option value="2016">2016 vs 2011</option></select><div class="tablewrap"><table><thead><tr><th>Baseline group / comparison</th><th>Estimate</th><th>95% CI</th><th>p-value</th></tr></thead><tbody id="extbody"></tbody></table></div><figure><img src="EXT" alt="Primary-school slope contrasts by baseline service access"><figcaption>Archive-standardized units and pointwise intervals. Directly compare the group-difference contrast, rather than comparing separate p-values.</figcaption></figure><div class="note"><b>Measurement changes interpretation:</b> primary-school outcomes are standardized within each wave. Raw-unit group differences are -0.120 schools per thousand children in 2020 (95% CI -0.217 to -0.024, p = 0.014). These are distinct estimands, not interchangeable estimates.</div></section>
<section><h2>Radius sensitivity</h2><figure><img src="RAD" alt="School-access slope contrasts at 100, 150 and 200 kilometre sample cutoffs"><figcaption>Cutoffs use distance to settlements active in 2001. Presence retains the full-panel standardization. Changing the radius changes the sampled population.</figcaption></figure></section>
<section><h2>Assumptions and limitations</h2><p>Settlement location is not random. Causal interpretation depends on conditional parallel trends, measurement comparability, and limited confounding or spillovers. Refugee arrivals occur together with humanitarian aid and policy responses. Parish clustering does not address all geographic dependence.</p><p>Missing controls exclude 1,055 rows. Health-tier measures stop in 2016 and road measures start in 2011. No imputation fills those structural gaps. The archive's binary binning excludes another seven observations.</p><p>Positive relative school-access relationships coexist with a decline in unweighted average raw access. Neither pattern alone establishes a causal national-level effect. Exploratory comparisons are not adjusted for multiple testing.</p></section>
<section><h2>Sources and reproduction</h2><p><a href="https://doi.org/10.1016/j.worlddev.2023.106203">Original study</a> · <a href="https://doi.org/10.7910/DVN/TXSZDC">Public replication archive, version 1.0</a></p><p>Run <code>python run_analysis.py</code>, then <code>python -m unittest discover -s tests -v</code> and <code>python build_outputs.py</code>. The project package includes the source files, provenance register, numerical tables, memo, teaching notebook, and seminar materials.</p><p><b>AI disclosure:</b> OpenAI Codex assisted with source inspection, code, drafting, and checks. Executed Python generates the estimates. No Claude Code use or independent human peer review is claimed.</p></section><footer>Prepared 8 October 2026. Independent portfolio project. Original research and data credited to Zhou, Grossman, and Ge.</footer></main><script>
const rep=REPDATA, ext=EXTDATA; const f=x=>Number(x).toFixed(3); document.getElementById('repbody').innerHTML=rep.map(r=>`<tr><td>${r.outcome}</td><td>${f(r.published_estimate)}</td><td>${f(r.estimate)}</td><td>${f(r.se)}</td><td>${r.n.toLocaleString()}</td><td>${r.coefficient_matches_rounding&&r.se_matches_rounding&&r.n_matches?'Matches':'Review'}</td></tr>`).join('');
function update(){let outcome=document.getElementById('outcome').value,year=Number(document.getElementById('year').value);document.getElementById('extbody').innerHTML=ext.filter(r=>r.outcome===outcome&&r.post_year===year).map(r=>`<tr><td>${r.group}</td><td>${f(r.estimate)}</td><td>${f(r.ci_low)} to ${f(r.ci_high)}</td><td>${f(r.p_value)}</td></tr>`).join('');} document.getElementById('outcome').addEventListener('change',update);document.getElementById('year').addEventListener('change',update);update();
</script></html>'''
for token,name in [('MAP','presence_map'),('REP','replication'),('EXT','extension'),('RAD','radius')]:pagehtml=pagehtml.replace('src="'+token+'"','src="'+embedded(name)+'"')
pagehtml=pagehtml.replace('REPDATA',json.dumps(records)).replace('EXTDATA',json.dumps(extrecords));(D/'index.html').write_text(pagehtml)
print('Created memo, figures, geographic audit, and self-contained explorer')
